name: Daily Workflow

on:
  schedule:
    - cron: "5 5 1-26 12 *"

jobs:
  create-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "Github Actions"

      - name: Download input
        run: |
          day=$(date +%d)
          url_day=$(echo $day | sed 's/^0*//')
          curl --cookie "session=${SESSION}" \
            -o AdventOfCode/Inputs/${day}.txt \
            "https://adventofcode.com/2021/day/${url_day}/input"
          truncate -s -1 AdventOfCode/Inputs/${day}.txt
        env:
          SESSION: ${{ secrets.AOC_SESSION_COOKIE }}

      - name: Create code and test files
        run: |
          day=$(date +%d)
          sed "s/day/$day/g" template/Day.cs > "AdventOfCode/Day_${day}.cs"
          sed "s/dayNo/$day/g" template/Day_Test.cs > "AdventOfCode.Tests/Day_${day}Test.cs"

      - name: Commit and push files
        run: |
          git add .
          git commit -m "Adding todays files"
          git push
