name: Daily Input

on:
  schedule:
    - cron: "5 5 * * *"

jobs:
  download-input:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download input
        run: |
          day=$(date +%d)
          url_day=$(echo $day | sed 's/^0*//')
          curl --cookie "session=${SESSION}" \
            -o AdventOfCode/Inputs/${day}.txt \
            "https://adventofcode.com/2021/day/${url_day}/input"
          truncate -s -1 AdventOfCode/Inputs/${day}.txt
        env:
          SESSION: ${{ secrets.AOC_SESSION_COOKIE }}

      - name: Commit input
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "Github Actions"
          git add .
          git commit -m "Adding todays input"
          git push
