on:
  push:
  schedule:
    - cron: "0 5 * * *"

jobs:
  download-input:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download input
        run: |
          day=$(date +%d)
          curl --cookie "session=${SESSION}" \
            -o AdventOfCode/Inputs/${day}.txt \
            https://adventofcode.com/2021/day/${day}/input
          cat AdventOfCode/Inputs/${day}.txt
        env:
          SESSION: ${{ secrets.AOC_SESSION_COOKIE }}
